services:
  postgres-empresa:
    image: postgres
    container_name: postgres-empresa
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
volumes:
  postgres-data: