server:
  port: 8081
spring:
  application:
    name: empresa-app

  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://database-1.ckkwgo0vfhk9.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

url:
  viacep.host: https://viacep.com.br/ws